### ISSUE TITLE
The CPAN release for this module should point at this repository

### ISSUE THREAD

**Issue by oalders** [jonasbn/perl-date-holidays-abstract#3]
Right now it uses the `gitpan` URL, which is a bit confusing.  

Ping @manwar (this came up when I searched MetaCPAN for gitpan URLs as we discussed earlier).

![image](https://user-images.githubusercontent.com/96205/64968658-86bd4b00-d870-11e9-9bb2-c963fff633cd.png)

**Comment by manwar** [comment]
That's how I ended up gitpan profile hosted repository.

**Comment by jonasbn** [comment]
I will investigate ASAP

**Comment by jonasbn** [comment]
Have released 0.08 addressing the described issue, thanks @oalders for the issue report

**Comment by oalders** [comment]
Thanks @jonasbn! 🚀
